### ISSUE TITLE
--ami-name option or similar for aegea launch

### ISSUE THREAD

**Issue by jamestwebber** [kislyuk/aegea#35]
We're building up a set of common AMIs for general Biohub users, and it'd be nice to launch them by AMI Name rather than ID. I don't believe this is possible unless I just didn't see the option.

**Comment by jamestwebber** [comment]
Per discussion on our repo it would be even _cooler_ if I could use `aegea launch --ami_name "czbiohub-something-*"` and always get the most recent image. We're going to be date-stamping our AMI names so people will have to know which one they need.

**Comment by kislyuk** [comment]
@jamestwebber sorry about the delay in my response. This is what the `--ami-tags` option is for. In EC2, resource names are actually just tags (key=value pairs) with the magical key `Name`. So you should be able to do what you want with `aegea launch --ami-tags Name=czbiohub-something`. From all the AMIs tagged with a given tag, aegea will choose the latest and launch that. You shouldn't need to put a date in your AMI name, since the creation date is already present among the metadata properties of the AMI.

**Comment by jamestwebber** [comment]
I think I'm missing some aspect of how EC2 images work. We're using [packer](https://www.packer.io/) to build the images and it doesn't allow multiple images to have the same name, which is why we're put the date in there. We're going to want to keep a record of old images to maintain reproducibility so we can't just overwrite them with the same name.

Or maybe it's just that `ami_name` is different from the tag `name`. The former is typically unique when I look at public images (e.g. the `*-ubuntu-xenial-16.04-amd64-server-*` AMIs all have dates on them). Should we be added a separate stable `name` tag to these images?

**Comment by jamestwebber** [comment]
Yeah I think that the second paragraph is the case–there is no way to specify the AMI Name (which tends to change based on build time). But we can start tagging our images with a separate `Name` that is generic and always picks the most recent build.

**Comment by jamestwebber** [comment]
I think the above answers my question–I'll add a name-tag to our images. I haven't tested the "most recent" angle but I'm going to assume it works for now and I'll open a new issue if I have a problem.
