### ISSUE TITLE
add support for amazon-linux-2022 ami

### ISSUE THREAD

**Issue by bkmartinjr** [kislyuk/aegea#74]
It would be nice to have the Amazon Linux 2022 equivalent of the launch `--amazon-linux-ami` option (which uses the most recent Amazon Linux 2 AMI)

**Comment by kislyuk** [comment]
Hi Bruce, good to hear from you.

I've released v4.3.2 which adds logic to select Amazon Linux 2022 and locate its most recent AMI. In your `~/.config/aegea/config.yml`, add the following:
```yaml
launch:
  amazon_linux_release: 2022
```
Please note however, that while the instance launches correctly, you can't `aegea ssh` to it using the standard (SSM-based) configuration out of the box. This is because Amazon Linux 2022 does not currently bundle the AWS SSM agent, which is necessary to tunnel to the instance without opening any firewall ports (and is what aegea uses by default): https://github.com/amazonlinux/amazon-linux-2022/issues/13

So, until they fix that, there is some extra work you'll need to do to ensure SSH connectivity to the instance. I can give a few pointers as far as getting the SSM agent installed at startup, but I'd prefer to wait for AWS to fix this instead of adding that custom logic to aegea.

**Comment by kislyuk** [comment]
Hi Bruce! Amazon re-added SSM to the Amazon Linux AMI and I also added support for the Amazon Linux 2023 release as well. Closing this issue :)
